[package]
name = "dive-mcp"
version = "0.1.0"
edition = "2024"

[features]
default = []
local_ipc = ["tokio-stream"]

[dependencies]
base64 = "0.22"
homedir = "0.3.6"
libdive-desktop = { workspace = true }
reqwest = { version = "0.12.24", features = ["json", "native-tls-vendored"] }
rmcp = { version = "0.10.0", features = ["elicitation"] }
schemars = "1.1.0"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", optional = true }

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true # Enables link-time-optimizations.
opt-level = "z" # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
