
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "core_js"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0", features = ["serde-json", "napi4", "napi6", "tokio_rt"]}
napi-derive = "3.0.0"
dive-core = { workspace = true }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
log = "0.4"
futures = "0.3.31"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
